require('impatient')
require("basicneovim")
require("functions")
require("plugins.plugins")
require("tools")
require("themes")
require("keymaps")
require("plugins.utils")
require("plugins.nvimtree")
require("setthings")
require("plugins.complete")
require("plugins.configs.bufferline")
require("plugins.configs.lsp-config.cmp")
require("plugins.configs.lsp-config.configlsp")
require("plugins.configs.lsp-config.emmet-lsp")

-- require("plugins.configs.cmpconfig")
